let dt = new Date();
dt.setFullYear(1995);
dt.setMonth(10);
dt.setDate(26);
dt.setHours(9);
dt.setMinutes(30);
dt.setSeconds(0);
dt.setMilliseconds(0);
console.log(dt.toString());
console.log(dt.toJSON());
console.log(dt.toUTCString());
console.log(dt.toLocaleString());
console.log(dt.toDateString());
console.log(dt.toTimeString());
console.log(dt.toLocaleDateString());
console.log(dt.toLocaleTimeString());
console.log(Date.now());
console.log(Date.parse('November 26, 1995 9:30:00'));
console.log(Date.UTC(1995, 10, 26, 1, 30, 0, 0));