var a = new Object();
console.log(a.toString());
console.log(a.valueOf());
var b = 100;
console.log(b.toString());
console.log(b.valueOf());
var c = '小明';
console.log(c.toString());
console.log(c.valueOf());
var d = new Date();
console.log(d.toString());
console.log(d.valueOf());